name: bowling-game
version: 1.0.0.0

dependencies:
  - base

library:
  exposed-modules: BowlingGame
  source-dirs: src
  ghc-options: -Wall
  # dependencies:
  # - foo       # List here the packages you
  # - bar       # want to use in your solution.

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - bowling-game
      - hspec
      - hspec-junit-formatter
