#!/usr/bin/env sh
#
# Copyright (c) 2022 Murex
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

OS=$(uname -s)

case ${OS} in
Darwin)
  CMAKE_BIN_PATH="./cmake/cmake-macos-universal/CMake.app/Contents/bin"
  CMAKE_CMD="${CMAKE_BIN_PATH}/cmake"
  CTEST_CMD="${CMAKE_BIN_PATH}/ctest"
  ;;
Linux)
  CMAKE_BIN_PATH="./cmake/cmake-linux-x86_64/bin"
  CMAKE_CMD="${CMAKE_BIN_PATH}/cmake"
  CTEST_CMD="${CMAKE_BIN_PATH}/ctest"
  ;;
MINGW64_NT-*)
  CMAKE_BIN_PATH="./build/cmake/cmake-windows-x86_64/bin"
  CMAKE_CMD="${CMAKE_BIN_PATH}/cmake.exe"
  CTEST_CMD="${CMAKE_BIN_PATH}/ctest.exe"
  ;;
*)
  tcr_error "OS ${OS} is currently not supported"
  ;;
esac

TCR_BUILD_CMD="${CMAKE_CMD} --build build --config Debug"
TCR_TEST_CMD="${CTEST_CMD} --output-on-failure --test-dir build --build-config Debug"
