# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  # Maintain dependencies for Maven
  - package-ecosystem: "maven"
    directory: "/java"
    schedule:
      interval: "weekly"

  # Maintain dependencies for Gradle
  - package-ecosystem: "gradle"
    directory: "/java"
    schedule:
      interval: "weekly"

  # Maintain dependencies for Go Modules
  - package-ecosystem: "gomod"
    directory: "/go"
    schedule:
      interval: "weekly"

  # Maintain dependencies for Nuget
  - package-ecosystem: "nuget"
    directory: "/csharp"
    schedule:
      interval: "weekly"

  # Maintain dependencies for Python
  - package-ecosystem: "pip"
    directory: "/python"
    schedule:
      interval: "weekly"

  # Maintain dependencies for Typescript
  - package-ecosystem: "npm"
    directory: "/typescript"
    schedule:
      interval: "weekly"

  # Maintain dependencies for Elixir examples
  - package-ecosystem: "mix"
    directory: "/elixir"
    schedule:
      interval: "weekly"
