[project]
name = "bowling_game"
requires-python = ">=3.10"

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
addopts = "-vvs --junitxml=\"pytest/result.xml\""
testpaths = [
    "tests"
]
