name: Cargo

permissions:
  contents: read
  actions: write

on:
  push:
    branches:
      - '**'
    paths:
      - 'rust/**'
  workflow_dispatch:
    inputs: { }

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Cargo build
        working-directory: rust
        run: cargo build
      - name: Cargo Test
        working-directory: rust
        run: cargo test
