name: Go

on:
  push:
    branches:
      - '**'
    paths:
      - 'go/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'
      - name: Build
        working-directory: go
        run: go build -v ./...
      - name: Test
        working-directory: go
        run: go test -v ./...
