name: Go

permissions:
  contents: read
  actions: write

on:
  push:
    branches:
      - '**'
    paths:
      - 'go/**'
  workflow_dispatch:
    inputs: { }

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
      - name: Build
        working-directory: go
        run: go build -v ./...
      - name: Test
        working-directory: go
        run: go test -v ./...
