name: Go

on:
  push:
    branches:
      - '**'
    paths:
      - 'go/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: Build
        run: |
          cd go
          go build -v ./...
      - name: Test
        run: |
          cd go
          go test -v ./...
