name: Gradle

on: 
  push:
    branches:
      - '**'
    paths:
      - 'java/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true
    - name: Set up JDK 11
      uses: actions/setup-java@v2.5.0
      with:
        distribution: 'zulu'
        java-version: 11
        java-package: jdk
    - name: Build with Gradle
      working-directory: java
      run: ./gradlew clean test --no-daemon
