name: Maven

on: 
  push:
    branches:
      - '**'
    paths:
      - 'java/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: 17
        java-package: jdk
    - name: Build with Maven
      working-directory: java
      run: ./mvnw --batch-mode --update-snapshots clean test
