name: Maven

on: 
  push:
    branches:
      - '**'
    paths:
      - 'java/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: 11
        java-package: jdk
    - name: Build with Maven
      working-directory: java
      run: ./mvnw --batch-mode --update-snapshots clean test
