name: Mix

permissions:
  contents: read
  actions: write

on:
  push:
    branches:
      - '**'
    paths:
      - 'elixir/**'
  workflow_dispatch:
    inputs: { }

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Beam
        uses: erlef/setup-beam@v1
        with:
          otp-version: '27'
          elixir-version: '1.18.0'
      - name: Dependencies
        working-directory: elixir
        run: mix deps.get
      - name: Build
        working-directory: elixir
        run: mix compile
      - name: Test
        working-directory: elixir
        run: mix test
